from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence


@dataclass(frozen=True)
class MacroIndicator:
    id: str
    name: str
    category: str
    frequency: str
    units: str
    source: str
    why_it_matters: str
    asset_impact: str
    direction_hint: str
    fred_series: str | None = None


@dataclass(frozen=True)
class MacroCategoryDef:
    id: str
    name: str
    indicators: Sequence[MacroIndicator]


RATES_CURVE = MacroCategoryDef(
    id="rates_curve",
    name="Rates & Curve",
    indicators=(
        MacroIndicator(
            id="fed_funds",
            name="Fed Funds Rate",
            category="Rates & Curve",
            frequency="daily",
            units="%",
            source="FRED",
            why_it_matters="Policy anchor for the entire curve.",
            asset_impact="SPX/NAS/USD",
            direction_hint="Higher = tighter financial conditions.",
            fred_series="DFF",
        ),
        MacroIndicator(
            id="sofr",
            name="SOFR",
            category="Rates & Curve",
            frequency="daily",
            units="%",
            source="FRED",
            why_it_matters="Overnight funding costs for risk assets.",
            asset_impact="USD/Rates",
            direction_hint="Higher = tighter liquidity.",
            fred_series="SOFR",
        ),
        MacroIndicator(
            id="us2y",
            name="US 2Y",
            category="Rates & Curve",
            frequency="daily",
            units="%",
            source="FRED",
            why_it_matters="Policy expectations and growth outlook.",
            asset_impact="Rates/USD",
            direction_hint="Higher = tighter expectations.",
            fred_series="DGS2",
        ),
        MacroIndicator(
            id="us10y",
            name="US 10Y",
            category="Rates & Curve",
            frequency="daily",
            units="%",
            source="FRED",
            why_it_matters="Benchmark long-term yield for risk pricing.",
            asset_impact="SPX/NAS",
            direction_hint="Higher = valuation headwind.",
            fred_series="DGS10",
        ),
        MacroIndicator(
            id="us30y",
            name="US 30Y",
            category="Rates & Curve",
            frequency="daily",
            units="%",
            source="FRED",
            why_it_matters="Long-duration discount rate signal.",
            asset_impact="Rates",
            direction_hint="Higher = duration pressure.",
            fred_series="DGS30",
        ),
        MacroIndicator(
            id="spread_2s10s",
            name="2s10s Spread",
            category="Rates & Curve",
            frequency="daily",
            units="pp",
            source="Derived",
            why_it_matters="Curve inversion risk signal.",
            asset_impact="SPX/NAS",
            direction_hint="Lower = recession risk.",
        ),
        MacroIndicator(
            id="real_yield_10y",
            name="10Y Real Yield",
            category="Rates & Curve",
            frequency="daily",
            units="%",
            source="FRED",
            why_it_matters="Real rates drive equity multiples.",
            asset_impact="SPX/NAS/Gold",
            direction_hint="Higher = risk-off/Gold headwind.",
            fred_series="DFII10",
        ),
        MacroIndicator(
            id="breakeven_5y",
            name="5Y Breakeven Inflation",
            category="Rates & Curve",
            frequency="daily",
            units="%",
            source="FRED",
            why_it_matters="Inflation expectations for policy path.",
            asset_impact="Rates/Gold",
            direction_hint="Higher = inflation risk.",
            fred_series="T5YIE",
        ),
    ),
)

CREDIT_STRESS = MacroCategoryDef(
    id="credit_stress",
    name="Credit & Financial Stress",
    indicators=(
        MacroIndicator(
            id="ig_spread",
            name="IG OAS",
            category="Credit & Financial Stress",
            frequency="daily",
            units="bps",
            source="FRED",
            why_it_matters="Investment-grade credit risk premium.",
            asset_impact="SPX/NAS",
            direction_hint="Higher = risk-off.",
            fred_series="BAMLC0A0CM",
        ),
        MacroIndicator(
            id="hy_spread",
            name="HY OAS",
            category="Credit & Financial Stress",
            frequency="daily",
            units="bps",
            source="FRED",
            why_it_matters="High-yield stress indicator.",
            asset_impact="SPX/NAS",
            direction_hint="Higher = risk-off.",
            fred_series="BAMLH0A0HYM2",
        ),
        MacroIndicator(
            id="ted_spread",
            name="TED Spread",
            category="Credit & Financial Stress",
            frequency="daily",
            units="bps",
            source="FRED",
            why_it_matters="Bank funding stress gauge.",
            asset_impact="USD/Rates",
            direction_hint="Higher = stress.",
            fred_series="TEDRATE",
        ),
        MacroIndicator(
            id="sloos",
            name="SLOOS Lending Standards",
            category="Credit & Financial Stress",
            frequency="quarterly",
            units="%",
            source="FRED",
            why_it_matters="Credit tightening for the real economy.",
            asset_impact="SPX/NAS",
            direction_hint="Higher = tighter credit.",
            fred_series="DRTSCILM",
        ),
    ),
)

LIQUIDITY = MacroCategoryDef(
    id="liquidity",
    name="Liquidity",
    indicators=(
        MacroIndicator(
            id="fed_balance_sheet",
            name="Fed Balance Sheet",
            category="Liquidity",
            frequency="weekly",
            units="$bn",
            source="FRED",
            why_it_matters="Liquidity supply to markets.",
            asset_impact="SPX/NAS",
            direction_hint="Higher = supportive.",
            fred_series="WALCL",
        ),
        MacroIndicator(
            id="rrp",
            name="Reverse Repo",
            category="Liquidity",
            frequency="daily",
            units="$bn",
            source="FRED",
            why_it_matters="Cash parked at the Fed.",
            asset_impact="SPX/NAS",
            direction_hint="Lower = more liquidity.",
            fred_series="RRPONTSYD",
        ),
        MacroIndicator(
            id="tga",
            name="Treasury General Account",
            category="Liquidity",
            frequency="daily",
            units="$bn",
            source="FRED",
            why_it_matters="Treasury cash balance impacts reserves.",
            asset_impact="SPX/NAS",
            direction_hint="Lower = more liquidity.",
            fred_series="WTREGEN",
        ),
        MacroIndicator(
            id="m2",
            name="M2 Money Supply",
            category="Liquidity",
            frequency="monthly",
            units="$bn",
            source="FRED",
            why_it_matters="Broad liquidity growth.",
            asset_impact="SPX/NAS",
            direction_hint="Higher = liquidity support.",
            fred_series="M2SL",
        ),
    ),
)

INFLATION = MacroCategoryDef(
    id="inflation",
    name="Inflation",
    indicators=(
        MacroIndicator(
            id="cpi",
            name="CPI",
            category="Inflation",
            frequency="monthly",
            units="%",
            source="FRED",
            why_it_matters="Consumer inflation trend.",
            asset_impact="Rates/Gold",
            direction_hint="Higher = tighter policy.",
            fred_series="CPIAUCSL",
        ),
        MacroIndicator(
            id="core_cpi",
            name="Core CPI",
            category="Inflation",
            frequency="monthly",
            units="%",
            source="FRED",
            why_it_matters="Inflation excluding food/energy.",
            asset_impact="Rates",
            direction_hint="Higher = tighter policy.",
            fred_series="CPILFESL",
        ),
        MacroIndicator(
            id="pce",
            name="PCE",
            category="Inflation",
            frequency="monthly",
            units="%",
            source="FRED",
            why_it_matters="Fed-preferred inflation gauge.",
            asset_impact="Rates",
            direction_hint="Higher = tighter policy.",
            fred_series="PCEPI",
        ),
        MacroIndicator(
            id="wage_growth",
            name="Wage Growth (AHE YoY)",
            category="Inflation",
            frequency="monthly",
            units="%",
            source="FRED",
            why_it_matters="Wage pressure feeds core inflation.",
            asset_impact="Rates",
            direction_hint="Higher = inflation risk.",
            fred_series="AHETPI",
        ),
    ),
)

GROWTH_DEMAND = MacroCategoryDef(
    id="growth_demand",
    name="Growth / Demand",
    indicators=(
        MacroIndicator(
            id="pmi",
            name="PMI/ISM",
            category="Growth / Demand",
            frequency="monthly",
            units="index",
            source="FRED",
            why_it_matters="Business activity pulse.",
            asset_impact="SPX/NAS",
            direction_hint="Higher = growth supportive.",
            fred_series="NAPM",
        ),
        MacroIndicator(
            id="retail_sales",
            name="Retail Sales",
            category="Growth / Demand",
            frequency="monthly",
            units="$bn",
            source="FRED",
            why_it_matters="Consumer demand strength.",
            asset_impact="SPX/NAS",
            direction_hint="Higher = demand support.",
            fred_series="RSAFS",
        ),
        MacroIndicator(
            id="industrial_production",
            name="Industrial Production",
            category="Growth / Demand",
            frequency="monthly",
            units="index",
            source="FRED",
            why_it_matters="Manufacturing cycle signal.",
            asset_impact="SPX/NAS",
            direction_hint="Higher = growth supportive.",
            fred_series="INDPRO",
        ),
        MacroIndicator(
            id="capacity_utilization",
            name="Capacity Utilization",
            category="Growth / Demand",
            frequency="monthly",
            units="%",
            source="FRED",
            why_it_matters="Slack and inflation pressure.",
            asset_impact="Rates",
            direction_hint="Higher = inflation risk.",
            fred_series="TCU",
        ),
        MacroIndicator(
            id="consumer_sentiment",
            name="Consumer Sentiment",
            category="Growth / Demand",
            frequency="monthly",
            units="index",
            source="FRED",
            why_it_matters="Household confidence gauge.",
            asset_impact="SPX",
            direction_hint="Higher = supportive.",
            fred_series="UMCSENT",
        ),
        MacroIndicator(
            id="housing_starts",
            name="Housing Starts",
            category="Growth / Demand",
            frequency="monthly",
            units="k",
            source="FRED",
            why_it_matters="Residential construction activity.",
            asset_impact="SPX",
            direction_hint="Higher = growth supportive.",
            fred_series="HOUST",
        ),
        MacroIndicator(
            id="building_permits",
            name="Building Permits",
            category="Growth / Demand",
            frequency="monthly",
            units="k",
            source="FRED",
            why_it_matters="Forward housing demand.",
            asset_impact="SPX",
            direction_hint="Higher = growth supportive.",
            fred_series="PERMIT",
        ),
        MacroIndicator(
            id="mortgage_30y",
            name="30Y Mortgage Rate",
            category="Growth / Demand",
            frequency="weekly",
            units="%",
            source="FRED",
            why_it_matters="Housing affordability signal.",
            asset_impact="SPX",
            direction_hint="Higher = demand headwind.",
            fred_series="MORTGAGE30US",
        ),
    ),
)

LABOR = MacroCategoryDef(
    id="labor",
    name="Labor",
    indicators=(
        MacroIndicator(
            id="nfp",
            name="Nonfarm Payrolls",
            category="Labor",
            frequency="monthly",
            units="k",
            source="FRED",
            why_it_matters="Labor market momentum.",
            asset_impact="SPX/NAS",
            direction_hint="Higher = growth supportive.",
            fred_series="PAYEMS",
        ),
        MacroIndicator(
            id="unemployment",
            name="Unemployment Rate",
            category="Labor",
            frequency="monthly",
            units="%",
            source="FRED",
            why_it_matters="Slack and recession risk.",
            asset_impact="SPX",
            direction_hint="Higher = risk-off.",
            fred_series="UNRATE",
        ),
        MacroIndicator(
            id="jobless_claims",
            name="Initial Jobless Claims",
            category="Labor",
            frequency="weekly",
            units="k",
            source="FRED",
            why_it_matters="High-frequency labor stress.",
            asset_impact="SPX",
            direction_hint="Higher = risk-off.",
            fred_series="ICSA",
        ),
        MacroIndicator(
            id="continuing_claims",
            name="Continuing Claims",
            category="Labor",
            frequency="weekly",
            units="k",
            source="FRED",
            why_it_matters="Labor slack persistence.",
            asset_impact="SPX",
            direction_hint="Higher = risk-off.",
            fred_series="CCSA",
        ),
        MacroIndicator(
            id="jolts",
            name="JOLTS Job Openings",
            category="Labor",
            frequency="monthly",
            units="k",
            source="FRED",
            why_it_matters="Hiring demand gauge.",
            asset_impact="SPX",
            direction_hint="Higher = growth supportive.",
            fred_series="JTSJOL",
        ),
    ),
)

RISK_VOL = MacroCategoryDef(
    id="risk_vol",
    name="Risk / Volatility / Positioning",
    indicators=(
        MacroIndicator(
            id="vix",
            name="VIX",
            category="Risk / Volatility / Positioning",
            frequency="daily",
            units="index",
            source="FRED",
            why_it_matters="Equity volatility proxy.",
            asset_impact="SPX",
            direction_hint="Higher = risk-off.",
            fred_series="VIXCLS",
        ),
        MacroIndicator(
            id="vvix",
            name="VVIX",
            category="Risk / Volatility / Positioning",
            frequency="daily",
            units="index",
            source="FRED",
            why_it_matters="Volatility of volatility.",
            asset_impact="SPX",
            direction_hint="Higher = risk-off.",
            fred_series="VVIX",
        ),
        MacroIndicator(
            id="move",
            name="MOVE",
            category="Risk / Volatility / Positioning",
            frequency="daily",
            units="index",
            source="FRED",
            why_it_matters="Rates volatility stress.",
            asset_impact="Rates",
            direction_hint="Higher = risk-off.",
            fred_series="MOVE",
        ),
        MacroIndicator(
            id="put_call",
            name="Put/Call Ratio",
            category="Risk / Volatility / Positioning",
            frequency="daily",
            units="ratio",
            source="Placeholder",
            why_it_matters="Positioning and hedging intensity.",
            asset_impact="SPX",
            direction_hint="Higher = defensive.",
            fred_series=None,
        ),
        MacroIndicator(
            id="cot",
            name="COT Positioning",
            category="Risk / Volatility / Positioning",
            frequency="weekly",
            units="index",
            source="Placeholder",
            why_it_matters="Speculative positioning tilt.",
            asset_impact="USD/Gold",
            direction_hint="Higher = speculative long.",
            fred_series=None,
        ),
    ),
)

ALL_CATEGORIES: Sequence[MacroCategoryDef] = (
    RATES_CURVE,
    CREDIT_STRESS,
    LIQUIDITY,
    INFLATION,
    GROWTH_DEMAND,
    LABOR,
    RISK_VOL,
)


def all_indicators() -> list[MacroIndicator]:
    return [indicator for category in ALL_CATEGORIES for indicator in category.indicators]


def find_indicator(indicator_id: str) -> MacroIndicator | None:
    for indicator in all_indicators():
        if indicator.id == indicator_id:
            return indicator
    return None
